#!/bin/bash

mkdir -p build_logs
BOXTYPE=$(cat config | grep "BOXTYPE=" | awk -F "=" '{print $2}')
LOGFILE=build_logs/make_$(echo $BOXTYPE)_$(date +%d.%m.%Y_%H%M).log

echo "--- DISTRIBUTION ---" > $LOGFILE
cat /etc/*release >> $LOGFILE
echo "----- GIT  REV -----" >> $LOGFILE
echo "rev: "$(git log | grep "^commit" | wc -l) >> $LOGFILE
echo "commit: "$(git log -1 --pretty=format:%H) >> $LOGFILE
echo "url: "$(git config --get remote.origin.url) >> $LOGFILE
echo "------ CONFIG ------" >> $LOGFILE
cat config >> $LOGFILE
echo "--- MAKE TARGETS ---" >> $LOGFILE
echo $* >> $LOGFILE
echo "---- BUILD  LOG ----" >> $LOGFILE

if [ ! -z $1 ] ; then
	time make V=1 $* 2>&1 | tee -a $LOGFILE
else
	echo "Usage: makelog some_commands"
fi
