#!/bin/sh

. /etc/profile

read model < /etc/model

if [ -e /var/etc/.firstboot ]; then
/usr/bin/passwd root <<EOF
root
root
EOF
  rm /var/etc/.firstboot
fi

mount -t proc proc /proc
mount -t sysfs sys /sys
mount -t tmpfs tmp /tmp
mount -t tmpfs media /media
mount -t tmpfs mnt /mnt
#mkdir -p /media/hdd
mkdir -p /dev/pts
mount -t devpts devpts /dev/pts
echo /sbin/mdev >/proc/sys/kernel/hotplug
mdev -s

echo "starting interface"
/etc/init.d/mountall start

echo "mounting everything"
/etc/init.d/mount_everything

export B_REFSW_BOXMODE=5
insmod /lib/modules/nexus.ko
/usr/bin/nxserver &
/usr/bin/dvb_init /lib/modules/dvb.ko &

while [ ! -c /dev/fb0 ]; do
  usleep 100000
done

# load moduls from modules.extra ( kerneloptions )
[ -f /var/etc/modules.extra ] && eval `awk '{ if ($1) print "insmod /lib/modules/" $1 ".ko " $2,$3,$4,$5,$6,$7,$8,$9 "; "}' < /var/etc/modules.extra`

if [ -e /var/backup_flash.tar.gz ]; then
  tar xvf /var/backup_flash.tar.gz -C /
  rm -f /var/backup_flash.tar.gz
fi

echo "[rcS] add mmcblks in /dev/block"
/etc/init.d/mmcblk-by-name

if [ -e /share/tuxbox/neutrino/icons/bootlogo.m2v ]; then
  showiframe /share/tuxbox/neutrino/icons/bootlogo.m2v
fi

/bin/initfb
echo 200 > /proc/stb/lcd/brightness
oled -tc "Booting...TC-NMP"

echo "setup network"
/etc/init.d/hostname start
/etc/init.d/portmap start
/usr/sbin/inetd
NFS=$(grep -c nfs /proc/cmdline)
  if [ "$NFS" -eq "1" ]; then
    echo "Booting from nfs, don't set network"
    elif [ -e /var/tuxbox/config/.bootargs ]; then
    echo "using ip set via bootargs, don't reset network"
  else
    if [ -e /etc/network/interfaces ]; then
      ip addr flush eth0
      /etc/init.d/networking stop
      DHCP=$(grep -c dhcp /etc/network/interfaces)
      if [ "$DHCP" -eq "1" ]; then
        echo "Starting dhcp"
        /etc/init.d/udhcpc start
      fi
      /etc/init.d/networking start
    fi
  fi
/sbin/ifconfig lo 127.0.0.1 up

# set dummy time
date -s "2017-01-01 00:00"

killall -9 showiframe

until false
do
    echo "starting GUI ->"
    chmod 755 /usr/bin/neutrino
    if [ -e /tmp/neutrino ]; then
      chmod 755 /tmp/neutrino
      /tmp/neutrino
    else
      /usr/bin/neutrino -v 0
    fi
    rtv=$?
    echo "GUI ended <- RTV: " $rtv
    case "$rtv" in
      0) echo "0"
        echo "SHUTDOWN"
      init 0;;
      1) echo "1"
        echo "REBOOT"
        oled -tc "      *-*       "
      init 6;;
      3) echo "3"
        echo "RESTART"
        oled -tc "    RESTART     "
      sync;;
      *) echo "*"
        echo -e "\033[01;31mERROR: $rtv\033[00m"
        oled -tc "    *ERROR*     "
      init 6;;
    esac
done
oled -tc "      *-*       "

#never reached
oled -tc "REBOOT $model"
echo "REBOOT $model"
reboot -f

